import "server-only";
import argon2 from "argon2";
import { cookies, headers } from "next/headers";
import { prisma } from "@/lib/db/prisma";
import { hashToken, randomToken } from "@/lib/security/crypto";
import { ApiError } from "@/lib/http/api";
import type { Permission } from "./permissions";
import { audit } from "@/modules/audit/service";
const COOKIE="ruvaya_admin_session", SESSION_MS=8*60*60*1000;
export async function login(email:string,password:string){const normalized=email.trim().toLowerCase();const user=await prisma.adminUser.findUnique({where:{email:normalized},include:{roles:{include:{role:{include:{permissions:{include:{permission:true}}}}}}}});if(!user||user.status!=="ACTIVE"||user.lockedUntil&&user.lockedUntil>new Date()||!await argon2.verify(user.passwordHash,password)){if(user){const failures=user.failedLoginCount+1;await prisma.adminUser.update({where:{id:user.id},data:{failedLoginCount:failures,lockedUntil:failures>=5?new Date(Date.now()+15*60_000):null}});}await audit({action:"AUTH_LOGIN_FAILED",entityType:"AdminUser",entityId:user?.id});throw new ApiError("UNAUTHORIZED","Invalid email or password",401);}const token=randomToken(),expiresAt=new Date(Date.now()+SESSION_MS);await prisma.$transaction([prisma.adminSession.create({data:{tokenHash:hashToken(token),userId:user.id,expiresAt}}),prisma.adminUser.update({where:{id:user.id},data:{failedLoginCount:0,lockedUntil:null,lastLoginAt:new Date()}})]);(await cookies()).set(COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",path:"/",expires:expiresAt});await audit({adminUserId:user.id,action:"AUTH_LOGIN",entityType:"AdminUser",entityId:user.id});return{id:user.id,email:user.email,displayName:user.displayName};}
export async function currentAdmin(){const token=(await cookies()).get(COOKIE)?.value;if(!token)return null;return prisma.adminUser.findFirst({where:{status:"ACTIVE",sessions:{some:{tokenHash:hashToken(token),revokedAt:null,expiresAt:{gt:new Date()}}}},include:{roles:{include:{role:{include:{permissions:{include:{permission:true}}}}}}}});}
export async function requireAdmin(permission?:Permission){const user=await currentAdmin();if(!user)throw new ApiError("UNAUTHORIZED","Admin authentication required",401);if(permission){const allowed=user.roles.some(({role})=>role.name==="SUPER_ADMIN"||role.permissions.some(({permission:p})=>p.key===permission));if(!allowed)throw new ApiError("FORBIDDEN","You do not have permission for this operation",403);}return user;}
export async function logout(){const token=(await cookies()).get(COOKIE)?.value;if(token)await prisma.adminSession.updateMany({where:{tokenHash:hashToken(token),revokedAt:null},data:{revokedAt:new Date()}});(await cookies()).delete(COOKIE);}
export async function requestPasswordReset(email:string){const user=await prisma.adminUser.findUnique({where:{email:email.trim().toLowerCase()}});if(!user)return null;const token=randomToken();await prisma.passwordResetToken.create({data:{tokenHash:hashToken(token),userId:user.id,expiresAt:new Date(Date.now()+30*60_000)}});await audit({adminUserId:user.id,action:"AUTH_PASSWORD_RESET_REQUESTED",entityType:"AdminUser",entityId:user.id});return process.env.NODE_ENV==="development"?token:null;}
export async function resetPassword(token:string,password:string){if(password.length<12)throw new ApiError("VALIDATION_ERROR","Password must be at least 12 characters",422);const record=await prisma.passwordResetToken.findUnique({where:{tokenHash:hashToken(token)}});if(!record||record.usedAt||record.expiresAt<=new Date())throw new ApiError("AUTH_EXPIRED","Reset link is invalid or expired",401);const passwordHash=await argon2.hash(password,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});await prisma.$transaction([prisma.adminUser.update({where:{id:record.userId},data:{passwordHash}}),prisma.passwordResetToken.update({where:{id:record.id},data:{usedAt:new Date()}}),prisma.adminSession.updateMany({where:{userId:record.userId,revokedAt:null},data:{revokedAt:new Date()}})]);}
export async function requestContext(){const h=await headers();return{requestId:h.get("x-request-id")??undefined,ipAddress:h.get("x-forwarded-for")?.split(",")[0],userAgent:h.get("user-agent")??undefined}}
