import "server-only";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { ApiError } from "@/lib/http/api";
import { audit } from "@/modules/audit/service";
import type { z } from "zod";
import type { variantInputSchema } from "./schemas";
type Input=z.infer<typeof variantInputSchema>;

const data=(input:Input)=>({sku:input.sku,color:input.color,colorLabel:input.colorLabel,colorHex:input.colorHex,size:input.size,position:input.position,regularPricePaise:input.regularPricePaise,salePricePaise:input.salePricePaise,costPricePaise:input.costPricePaise,lowStockThreshold:input.lowStockThreshold,active:input.active,weightGrams:input.weightGrams,mediaId:input.mediaId});
export async function createVariant(productId:string,input:Input,adminUserId:string){const product=await prisma.product.findFirst({where:{id:productId,deletedAt:null}});if(!product)throw new ApiError("NOT_FOUND","Product not found",404);try{const variant=await prisma.productVariant.create({data:{productId,...data(input),currentStock:input.openingStock}});if(input.openingStock)await prisma.inventoryAdjustment.create({data:{variantId:variant.id,delta:input.openingStock,previousStock:0,newStock:input.openingStock,reason:"OPENING_STOCK",adminUserId}});await audit({adminUserId,action:"PRODUCT_VARIANT_CREATED",entityType:"ProductVariant",entityId:variant.id,after:variant});return variant}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")throw new ApiError("CONFLICT","SKU or size/colour combination already exists",409);throw error}}
export async function updateVariant(id:string,input:Input,adminUserId:string){const before=await prisma.productVariant.findUnique({where:{id}});if(!before)throw new ApiError("NOT_FOUND","Variant not found",404);if(input.openingStock<before.reservedStock)throw new ApiError("CONFLICT","Stock cannot be below reserved stock",409);const delta=input.openingStock-before.currentStock;const updated=await prisma.$transaction(async tx=>{const row=await tx.productVariant.update({where:{id},data:{...data(input),currentStock:input.openingStock}});if(delta)await tx.inventoryAdjustment.create({data:{variantId:id,delta,previousStock:before.currentStock,newStock:input.openingStock,reason:"VARIANT_UPDATED",adminUserId}});return row},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});await audit({adminUserId,action:"PRODUCT_VARIANT_UPDATED",entityType:"ProductVariant",entityId:id,before,after:updated});return updated}
export async function archiveVariant(id:string,adminUserId:string){const before=await prisma.productVariant.findUnique({where:{id},include:{_count:{select:{orderItems:true,reservations:true}}}});if(!before)throw new ApiError("NOT_FOUND","Variant not found",404);if(before.reservedStock>0)throw new ApiError("CONFLICT","A variant with active reservations cannot be archived",409);const updated=await prisma.productVariant.update({where:{id},data:{active:false}});await audit({adminUserId,action:"PRODUCT_VARIANT_ARCHIVED",entityType:"ProductVariant",entityId:id,before,after:updated});return{archived:true,historicalReferences:before._count.orderItems>0}}
